export const getChannels = () => {
  return ['#ethereum',
  '#status',
  '#status-bounties',
  '#status-core-devs',
  '#status-desktop',
  '#status-core-dapps',
  '#status-peopleops',
  '#status-marketing',
  '#status-core-chat',
  '#status-desktop',
  '#statusphere',
  '#watercooler',
  '#ethdenver',
  '#teambuilding',
  '#project-coworkers',
  '#316-core-network-incentives',
  '#313-sticker-market',
  '#314-tribute-to-talk',
  '#317-dapp-store',
  '#321-teller-network']
}